version: "3"

vars:
  APP_NAME: jain-digitizer
  PYTHON: python
  CONDA_ENV: jain-digitizer

tasks:
  system-info:
    desc: Display system information (OS and Architecture)
    cmds:
      - echo "Operating System  {{OS}}"
      - echo "CPU Architecture {{ARCH}}"
  setup:
    desc: Create the conda environment
    cmds:
      - conda env create -f environment.yml

  run:
    desc: Run the application locally
    cmds:
      - |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src && {{.PYTHON}} -m jain_digitizer.desktop.main

  web:
    desc: Run the streamlit web interface
    cmds:
      - |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src && streamlit run src/jain_digitizer/web/app.py

  setup-dev:
    desc: Install development dependencies
    cmds:
      - pip install -e ".[dev]"

  test:
    desc: Run tests
    cmds:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/src && pytest test/

  build-prep:
    desc: Update version.py and pyproject.toml with latest git info (tag and commit)
    cmds:
      - |
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        VERSION=${TAG#v}
        COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
        
        if [ -f pyproject.toml ]; then
            sed "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml > pyproject.toml.tmp && mv pyproject.toml.tmp pyproject.toml
        fi
        
        VERSION_FILE="src/jain_digitizer/version.py"
        printf "__version__ = \"%s\"\n__commit__ = \"%s\"\n" "$VERSION" "$COMMIT" > "$VERSION_FILE"
        echo "Injecting version $VERSION and commit $COMMIT"

  build-exe:
    desc: Build the executable locally
    deps: [build-prep]
    cmds:
      - |        
        pyinstaller \
          --noconfirm \
          --onefile \
          --windowed \
          --paths src \
          --icon=src/jain_digitizer/desktop/icon.png \
          --name {{.APP_NAME}}-{{OS}}-{{ARCH}} \
          --osx-bundle-identifier  me.yogendra.jain-digitizer \
          --add-data src/jain_digitizer/desktop/icon.png:jain_digitizer/desktop \
          --add-data src/jain_digitizer/common/prompt-html.md:jain_digitizer/common \
          --add-data src/jain_digitizer/common/prompt-md.md:jain_digitizer/common \
          src/jain_digitizer/desktop/main.py

  trigger-release:
    desc: Auto-increment version, tag, and push
    summary: |
      This task:
      1. Checks for uncommitted changes
      2. Gets the latest tag and increments the patch version
      3. Creates a new tag
      4. Pushes the branch and the new tag to trigger GitHub Actions
    preconditions:
      - sh: git diff-index --quiet HEAD --
        msg: "[ERROR] Uncommitted changes found. Please commit or stash them first."
    cmds:
      - |
        LATEST=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        NEXT_VERSION=$({{.PYTHON}} -c "v = '$LATEST'.lstrip('v').split('.'); v[-1] = str(int(v[-1]) + 1); print('.'.join(v))")
        echo "Calculated next version: v$NEXT_VERSION"
        git tag -a v$NEXT_VERSION -m "Release v$NEXT_VERSION"
        git push origin $(git branch --show-current)
        git push origin v$NEXT_VERSION
  release:
    desc: Alias for trigger-release
    cmds:
      - task: trigger-release

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build/ dist/ *.spec
