version: "3"

vars:
  APP_NAME: jain-digitizer
  PYTHON: python
  CONDA_ENV: jain-digitizer

tasks:
  system-info:
    desc: Display system information (OS and Architecture)
    cmds:
      - echo "Operating System  {{OS}}"
      - echo "CPU Architecture {{ARCH}}"
  setup:
    desc: Create the conda environment
    cmds:
      - conda env create -f environment.yml

  run:
    desc: Run the application locally
    cmds:
      - |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src && {{.PYTHON}} -m jain_digitizer.desktop.main

  web:
    desc: Run the streamlit web interface
    cmds:
      - |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src && streamlit run src/jain_digitizer/web/app.py

  setup-dev:
    desc: Install development dependencies
    cmds:
      - pip install -e ".[dev]"

  test:
    desc: Run tests
    cmds:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/src && pytest test/

  build-exe:
    desc: Build the executable locally
    cmds:
      - |        
        pyinstaller \
          --noconfirm \
          --onefile \
          --windowed \
          --paths src \
          --icon=src/jain_digitizer/desktop/icon.png \
          --name {{.APP_NAME}}-{{OS}}-{{ARCH}} \
          --osx-bundle-identifier  me.yogendra.jain-digitizer \
          --add-data src/jain_digitizer/desktop/icon.png:jain_digitizer/desktop \
          --add-data src/jain_digitizer/common/prompt-html.md:jain_digitizer/common \
          --add-data src/jain_digitizer/common/prompt-md.md:jain_digitizer/common \
          src/jain_digitizer/desktop/main.py

  commit:
    desc: Stage all changes and commit with a message
    cmds:
      - git add .
      - git commit -m "{{.MSG}}"
    requires:
      vars: [MSG]

  publish-pip:
    desc: Build and upload to PyPI
    cmds:
      - python -m build
      - twine upload dist/*

  publish-conda:
    desc: Build and upload to Anaconda
    cmds:
      - conda build conda/
      - anaconda upload $(conda build conda/ --output)

  release:
    desc: Create and push a new version tag
    cmds:
      - git tag v{{.VER}}
      - git push origin v{{.VER}}
      - echo "Tag v{{.VER}} pushed. GitHub Actions will now start the build."
    requires:
      vars: [VER]

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build/ dist/ *.spec
