name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }})
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: amd64
            built: jain-digitizer-windows-amd64.exe
            release: jain-digitizer-windows-amd64.exe
          - os: macos-latest
            arch: arm64
            built: jain-digitizer-darwin-arm64.app
            release: jain-digitizer-darwin-arm64.app.zip
          - os: ubuntu-latest
            arch: amd64
            built: jain-digitizer-linux-amd64
            release: jain-digitizer-linux-amd64
          - os: ubuntu-24.04-arm
            arch: arm64
            built: jain-digitizer-linux-arm64
            release: jain-digitizer-linux-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Cache Conda packages
        uses: actions/cache@v4
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-${{ runner.arch }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-conda-${{ env.CACHE_NUMBER }}-
            ${{ runner.os }}-${{ runner.arch }}-conda-

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: jain-digitizer
          environment-file: environment.yml
          auto-activate-base: false
          use-mamba: true
          pkgs-dirs: ~/conda_pkgs_dir
          use-only-tar-bz2: true

      - name: Build with PyInstaller
        shell: bash -l {0}
        run: |
          echo "Building for ${{ matrix.os }} (${{ matrix.arch }}):: ${{ matrix.built }}"
          task build-exe
          
          if [[ "${{ matrix.os }}" == macos-* ]]; then
            echo "Zipping macOS bundle..."
            cd dist
            zip -r "${{ matrix.release }}" "${{ matrix.built }}"
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ matrix.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
